pipeline {
    agent any

    environment {

        AWS_REGION = "ap-south-1"
        AWS_ACCOUNT_ID = "<AWS-ACCOUNT-ID>" #replace your aws account id

        ECR_REPO = "open-telemetry-registry" #replace you ECR repo name

        IMAGE_NAME = "cart"

        IMAGE_TAG = "${BUILD_NUMBER}"

        ECR_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"

        K8S_DEPLOYMENT = "opentelemetry-demo-cartservice"
        NAMESPACE = "default"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Astronomy-NextGenIT/Open-telemetry-Mono-repo.git'
            }
        }

        stage('Verify Tools') {
            steps {
                sh '''
                aws --version
                kubectl version --client
                docker --version
                '''
            }
        }

        stage('ECR Login') {
            steps {
                sh '''
                aws ecr get-login-password \
                --region ${AWS_REGION} | \
                docker login \
                --username AWS \
                --password-stdin \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build \
                -t ${IMAGE_NAME}:${IMAGE_TAG} \
                -f src/cart/src/Dockerfile .
                '''
            }
        }

        stage('Tag Image') {
            steps {
                sh '''
                docker tag \
                ${IMAGE_NAME}:${IMAGE_TAG} \
                ${ECR_URI}:${IMAGE_TAG}
                '''
            }
        }

        stage('Push Image To ECR') {
            steps {
                sh '''
                docker push ${ECR_URI}:${IMAGE_TAG}
                '''
            }
        }

        stage('Update Manifest') {
            steps {
                sh '''
                sed -i "s|ghcr.io/open-telemetry/demo:1.12.0-cartservice|${ECR_URI}:${IMAGE_TAG}|g" \
                src/cart/kubernetes/cart/deploy.yaml

                echo "Updated Images:"
                grep -n "image:" src/cart/kubernetes/cart/deploy.yaml
                '''
            }
        }

        stage('Deploy To Kubernetes') {
            steps {
                sh '''
                kubectl apply -f src/cart/kubernetes/cart/deploy.yaml
                kubectl apply -f src/cart/kubernetes/cart/svc.yaml
                '''
            }
        }

        stage('Rollout Status') {
            steps {
                sh '''
                kubectl rollout status deployment/${K8S_DEPLOYMENT} -n ${NAMESPACE}
                '''
            }
        }
    }

    post {

        success {
            echo 'Cart Service Deployment Successful'
        }

        failure {
            echo 'Pipeline Failed'
        }

        always {
            sh '''
            docker image prune -f || true
            '''
        }
    }
}
